configuration:
  global:
    log_to_console: true
    temporary_path: /home/jack/Projects/MetodoSugarSync/tmp
    v2: hello
  commands:
      "sync:test":
        v1: this is for the command "test"
      "sync:up":
        description: Synchronize upwards
        sync:
          - Mekit\Sync\Metodo\MetodoSync
      "sync:down":
        description: Synchronize downwards
        sync:
          - Mekit\Sync\Metodo\MetodoSync